/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as BalanceSheetRouteImport } from './routes/balance-sheet'
import { Route as CashFlowRouteImport } from './routes/cash-flow'
import { Route as DreRouteImport } from './routes/dre'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as JournalsRouteImport } from './routes/journals'
import { Route as PayablesRouteImport } from './routes/payables'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as StatementsRouteImport } from './routes/statements'
import { Route as TaxesRouteImport } from './routes/taxes'
import { Route as TrialBalanceRouteImport } from './routes/trial-balance'
import { Route as ParametersIndexRouteImport } from './routes/parameters/index'
import { Route as ParametersCostCentersRouteImport } from './routes/parameters/cost-centers'
import { Route as ParametersCurrenciesRouteImport } from './routes/parameters/currencies'
import { Route as ParametersExpenseCategoriesRouteImport } from './routes/parameters/expense-categories'
import { Route as ParametersFiscalPeriodsRouteImport } from './routes/parameters/fiscal-periods'
import { Route as ParametersPaymentTermsRouteImport } from './routes/parameters/payment-terms'
import { Route as ParametersTaxJurisdictionsRouteImport } from './routes/parameters/tax-jurisdictions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceSheetRoute = BalanceSheetRouteImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowRoute = CashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DreRoute = DreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsRoute = JournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => rootRouteImport,
} as any)
const PayablesRoute = PayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsRoute = StatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialBalanceRoute = TrialBalanceRouteImport.update({
  id: '/trial-balance',
  path: '/trial-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametersIndexRoute = ParametersIndexRouteImport.update({
  id: '/parameters/',
  path: '/parameters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametersCostCentersRoute = ParametersCostCentersRouteImport.update({
  id: '/parameters/cost-centers',
  path: '/parameters/cost-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametersCurrenciesRoute = ParametersCurrenciesRouteImport.update({
  id: '/parameters/currencies',
  path: '/parameters/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametersExpenseCategoriesRoute =
  ParametersExpenseCategoriesRouteImport.update({
    id: '/parameters/expense-categories',
    path: '/parameters/expense-categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParametersFiscalPeriodsRoute = ParametersFiscalPeriodsRouteImport.update({
  id: '/parameters/fiscal-periods',
  path: '/parameters/fiscal-periods',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametersPaymentTermsRoute = ParametersPaymentTermsRouteImport.update({
  id: '/parameters/payment-terms',
  path: '/parameters/payment-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametersTaxJurisdictionsRoute =
  ParametersTaxJurisdictionsRouteImport.update({
    id: '/parameters/tax-jurisdictions',
    path: '/parameters/tax-jurisdictions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/audit-log': typeof AuditLogRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/cash-flow': typeof CashFlowRoute
  '/dre': typeof DreRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/journals': typeof JournalsRoute
  '/payables': typeof PayablesRoute
  '/projects': typeof ProjectsRoute
  '/receivables': typeof ReceivablesRoute
  '/statements': typeof StatementsRoute
  '/taxes': typeof TaxesRoute
  '/trial-balance': typeof TrialBalanceRoute
  '/parameters/cost-centers': typeof ParametersCostCentersRoute
  '/parameters/currencies': typeof ParametersCurrenciesRoute
  '/parameters/expense-categories': typeof ParametersExpenseCategoriesRoute
  '/parameters/fiscal-periods': typeof ParametersFiscalPeriodsRoute
  '/parameters/payment-terms': typeof ParametersPaymentTermsRoute
  '/parameters/tax-jurisdictions': typeof ParametersTaxJurisdictionsRoute
  '/parameters/': typeof ParametersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/audit-log': typeof AuditLogRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/cash-flow': typeof CashFlowRoute
  '/dre': typeof DreRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/journals': typeof JournalsRoute
  '/payables': typeof PayablesRoute
  '/projects': typeof ProjectsRoute
  '/receivables': typeof ReceivablesRoute
  '/statements': typeof StatementsRoute
  '/taxes': typeof TaxesRoute
  '/trial-balance': typeof TrialBalanceRoute
  '/parameters/cost-centers': typeof ParametersCostCentersRoute
  '/parameters/currencies': typeof ParametersCurrenciesRoute
  '/parameters/expense-categories': typeof ParametersExpenseCategoriesRoute
  '/parameters/fiscal-periods': typeof ParametersFiscalPeriodsRoute
  '/parameters/payment-terms': typeof ParametersPaymentTermsRoute
  '/parameters/tax-jurisdictions': typeof ParametersTaxJurisdictionsRoute
  '/parameters': typeof ParametersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/audit-log': typeof AuditLogRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/cash-flow': typeof CashFlowRoute
  '/dre': typeof DreRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/journals': typeof JournalsRoute
  '/payables': typeof PayablesRoute
  '/projects': typeof ProjectsRoute
  '/receivables': typeof ReceivablesRoute
  '/statements': typeof StatementsRoute
  '/taxes': typeof TaxesRoute
  '/trial-balance': typeof TrialBalanceRoute
  '/parameters/cost-centers': typeof ParametersCostCentersRoute
  '/parameters/currencies': typeof ParametersCurrenciesRoute
  '/parameters/expense-categories': typeof ParametersExpenseCategoriesRoute
  '/parameters/fiscal-periods': typeof ParametersFiscalPeriodsRoute
  '/parameters/payment-terms': typeof ParametersPaymentTermsRoute
  '/parameters/tax-jurisdictions': typeof ParametersTaxJurisdictionsRoute
  '/parameters/': typeof ParametersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/accounts'
    | '/audit-log'
    | '/balance-sheet'
    | '/cash-flow'
    | '/dre'
    | '/inventory'
    | '/invoices'
    | '/journals'
    | '/payables'
    | '/projects'
    | '/receivables'
    | '/statements'
    | '/taxes'
    | '/trial-balance'
    | '/parameters/cost-centers'
    | '/parameters/currencies'
    | '/parameters/expense-categories'
    | '/parameters/fiscal-periods'
    | '/parameters/payment-terms'
    | '/parameters/tax-jurisdictions'
    | '/parameters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/accounts'
    | '/audit-log'
    | '/balance-sheet'
    | '/cash-flow'
    | '/dre'
    | '/inventory'
    | '/invoices'
    | '/journals'
    | '/payables'
    | '/projects'
    | '/receivables'
    | '/statements'
    | '/taxes'
    | '/trial-balance'
    | '/parameters/cost-centers'
    | '/parameters/currencies'
    | '/parameters/expense-categories'
    | '/parameters/fiscal-periods'
    | '/parameters/payment-terms'
    | '/parameters/tax-jurisdictions'
    | '/parameters'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/accounts'
    | '/audit-log'
    | '/balance-sheet'
    | '/cash-flow'
    | '/dre'
    | '/inventory'
    | '/invoices'
    | '/journals'
    | '/payables'
    | '/projects'
    | '/receivables'
    | '/statements'
    | '/taxes'
    | '/trial-balance'
    | '/parameters/cost-centers'
    | '/parameters/currencies'
    | '/parameters/expense-categories'
    | '/parameters/fiscal-periods'
    | '/parameters/payment-terms'
    | '/parameters/tax-jurisdictions'
    | '/parameters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AccountsRoute: typeof AccountsRoute
  AuditLogRoute: typeof AuditLogRoute
  BalanceSheetRoute: typeof BalanceSheetRoute
  CashFlowRoute: typeof CashFlowRoute
  DreRoute: typeof DreRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  JournalsRoute: typeof JournalsRoute
  PayablesRoute: typeof PayablesRoute
  ProjectsRoute: typeof ProjectsRoute
  ReceivablesRoute: typeof ReceivablesRoute
  StatementsRoute: typeof StatementsRoute
  TaxesRoute: typeof TaxesRoute
  TrialBalanceRoute: typeof TrialBalanceRoute
  ParametersCostCentersRoute: typeof ParametersCostCentersRoute
  ParametersCurrenciesRoute: typeof ParametersCurrenciesRoute
  ParametersExpenseCategoriesRoute: typeof ParametersExpenseCategoriesRoute
  ParametersFiscalPeriodsRoute: typeof ParametersFiscalPeriodsRoute
  ParametersPaymentTermsRoute: typeof ParametersPaymentTermsRoute
  ParametersTaxJurisdictionsRoute: typeof ParametersTaxJurisdictionsRoute
  ParametersIndexRoute: typeof ParametersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance-sheet': {
      id: '/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/balance-sheet'
      preLoaderRoute: typeof BalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow': {
      id: '/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof CashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dre': {
      id: '/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof DreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals': {
      id: '/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof JournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payables': {
      id: '/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof PayablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements': {
      id: '/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial-balance': {
      id: '/trial-balance'
      path: '/trial-balance'
      fullPath: '/trial-balance'
      preLoaderRoute: typeof TrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parameters/': {
      id: '/parameters/'
      path: '/parameters'
      fullPath: '/parameters/'
      preLoaderRoute: typeof ParametersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parameters/cost-centers': {
      id: '/parameters/cost-centers'
      path: '/parameters/cost-centers'
      fullPath: '/parameters/cost-centers'
      preLoaderRoute: typeof ParametersCostCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parameters/currencies': {
      id: '/parameters/currencies'
      path: '/parameters/currencies'
      fullPath: '/parameters/currencies'
      preLoaderRoute: typeof ParametersCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parameters/expense-categories': {
      id: '/parameters/expense-categories'
      path: '/parameters/expense-categories'
      fullPath: '/parameters/expense-categories'
      preLoaderRoute: typeof ParametersExpenseCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parameters/fiscal-periods': {
      id: '/parameters/fiscal-periods'
      path: '/parameters/fiscal-periods'
      fullPath: '/parameters/fiscal-periods'
      preLoaderRoute: typeof ParametersFiscalPeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parameters/payment-terms': {
      id: '/parameters/payment-terms'
      path: '/parameters/payment-terms'
      fullPath: '/parameters/payment-terms'
      preLoaderRoute: typeof ParametersPaymentTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parameters/tax-jurisdictions': {
      id: '/parameters/tax-jurisdictions'
      path: '/parameters/tax-jurisdictions'
      fullPath: '/parameters/tax-jurisdictions'
      preLoaderRoute: typeof ParametersTaxJurisdictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AccountsRoute: AccountsRoute,
  AuditLogRoute: AuditLogRoute,
  BalanceSheetRoute: BalanceSheetRoute,
  CashFlowRoute: CashFlowRoute,
  DreRoute: DreRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  JournalsRoute: JournalsRoute,
  PayablesRoute: PayablesRoute,
  ProjectsRoute: ProjectsRoute,
  ReceivablesRoute: ReceivablesRoute,
  StatementsRoute: StatementsRoute,
  TaxesRoute: TaxesRoute,
  TrialBalanceRoute: TrialBalanceRoute,
  ParametersCostCentersRoute: ParametersCostCentersRoute,
  ParametersCurrenciesRoute: ParametersCurrenciesRoute,
  ParametersExpenseCategoriesRoute: ParametersExpenseCategoriesRoute,
  ParametersFiscalPeriodsRoute: ParametersFiscalPeriodsRoute,
  ParametersPaymentTermsRoute: ParametersPaymentTermsRoute,
  ParametersTaxJurisdictionsRoute: ParametersTaxJurisdictionsRoute,
  ParametersIndexRoute: ParametersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
