/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as CashFlowRouteImport } from './routes/cash-flow'
import { Route as DreRouteImport } from './routes/dre'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as JournalsRouteImport } from './routes/journals'
import { Route as PayablesRouteImport } from './routes/payables'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as StatementsRouteImport } from './routes/statements'
import { Route as TaxesRouteImport } from './routes/taxes'
import { Route as TrialBalanceRouteImport } from './routes/trial-balance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowRoute = CashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DreRoute = DreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsRoute = JournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => rootRouteImport,
} as any)
const PayablesRoute = PayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsRoute = StatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialBalanceRoute = TrialBalanceRouteImport.update({
  id: '/trial-balance',
  path: '/trial-balance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/cash-flow': typeof CashFlowRoute
  '/dre': typeof DreRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/journals': typeof JournalsRoute
  '/payables': typeof PayablesRoute
  '/receivables': typeof ReceivablesRoute
  '/statements': typeof StatementsRoute
  '/taxes': typeof TaxesRoute
  '/trial-balance': typeof TrialBalanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/cash-flow': typeof CashFlowRoute
  '/dre': typeof DreRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/journals': typeof JournalsRoute
  '/payables': typeof PayablesRoute
  '/receivables': typeof ReceivablesRoute
  '/statements': typeof StatementsRoute
  '/taxes': typeof TaxesRoute
  '/trial-balance': typeof TrialBalanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/cash-flow': typeof CashFlowRoute
  '/dre': typeof DreRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/journals': typeof JournalsRoute
  '/payables': typeof PayablesRoute
  '/receivables': typeof ReceivablesRoute
  '/statements': typeof StatementsRoute
  '/taxes': typeof TaxesRoute
  '/trial-balance': typeof TrialBalanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/accounts'
    | '/cash-flow'
    | '/dre'
    | '/inventory'
    | '/invoices'
    | '/journals'
    | '/payables'
    | '/receivables'
    | '/statements'
    | '/taxes'
    | '/trial-balance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/accounts'
    | '/cash-flow'
    | '/dre'
    | '/inventory'
    | '/invoices'
    | '/journals'
    | '/payables'
    | '/receivables'
    | '/statements'
    | '/taxes'
    | '/trial-balance'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/accounts'
    | '/cash-flow'
    | '/dre'
    | '/inventory'
    | '/invoices'
    | '/journals'
    | '/payables'
    | '/receivables'
    | '/statements'
    | '/taxes'
    | '/trial-balance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AccountsRoute: typeof AccountsRoute
  CashFlowRoute: typeof CashFlowRoute
  DreRoute: typeof DreRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  JournalsRoute: typeof JournalsRoute
  PayablesRoute: typeof PayablesRoute
  ReceivablesRoute: typeof ReceivablesRoute
  StatementsRoute: typeof StatementsRoute
  TaxesRoute: typeof TaxesRoute
  TrialBalanceRoute: typeof TrialBalanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow': {
      id: '/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof CashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dre': {
      id: '/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof DreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals': {
      id: '/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof JournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payables': {
      id: '/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof PayablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements': {
      id: '/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial-balance': {
      id: '/trial-balance'
      path: '/trial-balance'
      fullPath: '/trial-balance'
      preLoaderRoute: typeof TrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AccountsRoute: AccountsRoute,
  CashFlowRoute: CashFlowRoute,
  DreRoute: DreRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  JournalsRoute: JournalsRoute,
  PayablesRoute: PayablesRoute,
  ReceivablesRoute: ReceivablesRoute,
  StatementsRoute: StatementsRoute,
  TaxesRoute: TaxesRoute,
  TrialBalanceRoute: TrialBalanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
